### ISSUE TITLE
adding GPRS Tunneling Protocol

### ISSUE THREAD

**Issue by ghost** [theclam/stripe#2]
Hi again, 
You did a great job, but why not adding GPT detection?
I guess it's the simplest one without using any tag, and that would be great if you could add it too. 

Thanks

**Comment by theclam** [comment]
I'll look into it - I assume it would be fairly straightforward to add. If you have some sample pcap files I'd be grateful as I don't work with mobile backhaul any more!

Thanks,

Foeh

**Comment by ghost** [comment]
hi,
here i upload a sample:
http://stuff.asis.io/GTP.pcap

**Comment by theclam** [comment]
OK, the spec was a little confusing around backward compatibility but I've added some code that I _think_ should handle GTPv1 / v2. It seems happy with the stuff in your capture file anyway. Can you please give it a try and let me know how it does?

Thanks,

Foeh

**Comment by theclam** [comment]
Since I've not heard anything for about 3 weeks I'm going to close the problem down, as far as I can see stripe handles the GTP encap in your example file OK but if you find any problems please let me know.

Regards,

Foeh
