### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jurajmat** [theclam/stripe#3]
Hello,

after testing stripe on the pcap testing sample everything worked fine, but when I used a bigger file (1GB, the same format as test sample) during decapsulating process a Segmentation failed (core dump) error appeared …

**Comment by theclam** [comment]
Hi,

Does the crash happen in the decapsulation or reassembly stage? Are you able to share the pcap file?

Thanks,

Foeh

**Comment by fact0real** [comment]
Hello,
I got Segmentation fault: 11 in Decapsulating... stage too.
`Darwin iThinkmate 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 16 23:12:31 PDT 2015; root:xnu-2782.20.48~4/RELEASE_X86_64 x86_64`
thanks
factoreal

**Comment by theclam** [comment]
Hi,
Would it be possible to get a copy of the pcap file? If not, I've pushed an update which adds a "-v" flag to turn on some debugging which would be helpful to pin down the problem. I'm on a Windows machine at the moment so I can't update the Mac binary right now so you will need to compile from source (or wait).
Thanks,
Foeh

**Comment by yalla** [comment]
@fact0real Could you try my patch with the same file and check if that solves your SEGFAULT?

**Comment by theclam** [comment]
OK... thanks, yalla, for putting me onto valgrind (can you tell I'm not a programmer?) it proved decisive in figuring this one out. I found a horrible typo in one of my mallocs which meant that the re-assembly routine was writing all over memory it didn't own. That's now fixed so the SEGFAULTs should stop. I've also put some code in to recover unused memory between multiple iterations of re-assembly. There is still some tidying up to do but on one of my pcaps the leak reduced from 55MB to 400KB.

**Comment by theclam** [comment]
Fixed another leak, total leakage is down to about 3k now which I think I can live with considering the pcap file I'm using is 100MB. If there's no feedback in a week or so I'll consider this one fixed and close the issue. Thanks for your help :)

**Comment by yalla** [comment]
No worries, glad to help; though I didn't have a bigger Gn-trace at hand to check out if it worked for me. However, I'll test it at the next possible opportunity :-)

**Comment by theclam** [comment]
I'm pretty sure this is now fixed but there's been no confirmation either way. I'll close the issue and I'm sure another will be opened if the problem persists. Thanks again, Yalla.
